### ISSUE TITLE
Robot bringup

### ISSUE THREAD

**Issue by fcuellar13** [team581/2024-offseason-bot#34] opened 2024-09-19 01:03 UTC
- Motor ID spreadsheet:  https://docs.google.com/spreadsheets/d/1zQ2vGFRMg89XwaUJMt96G3RbRwWmUXK5Ax2poAKG11Y/edit?gid=0#gid=0

**Comment by jonahsnider** [comment] 2024-09-19 21:58
Duplicate of #20

**Closed by jonahsnider** 2024-09-19 21:58 UTC
